networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

services:
  db:
    image: postgres:16-alpine
    container_name: app-db
    restart: unless-stopped
    env_file: ./envs/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: app-backend
    restart: unless-stopped
    env_file: ./envs/backend.env
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../frontend
      dockerfile: dockerfile
    container_name: app-frontend
    restart: unless-stopped
    env_file: ./envs/frontend.env0
    ports:
      - "51773:5173"
    networks:
      - app-network
    depends_on:
      - backend